/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one agent turn; may return an inert booking proposal + confirmation token
         * @description Drives the real tool loop (runAgentTurn) and maps its outcome to one of four arms. The `proposal` arm is the ONLY one carrying a token — minted server-side via the gate after the loop produces the inert create_booking proposal (this is proposing; nothing is executed until the token is redeemed). Stateless per request: `conversation_id` is minted if absent and echoed back so the client can continue the thread; NO conversation state is persisted (that is L4). `502` (code `LLM_UNAVAILABLE`) is the expected free-tier outage — every LLM provider in the chain rate-limited/exhausted — not an internal bug.
         */
        post: operations["postTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/confirmations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The non-secret confirmation card for a token (renders the gate UI)
         * @description Returns the current card state. Deliberately does NOT re-emit the token — the caller already holds it — so refetching/polling the card is safe. Polling this endpoint is how the client resolves a `202 in_progress` redeem.
         */
        get: operations["getConfirmation"];
        put?: never;
        /**
         * Redeem the token — the single user click that executes the booking
         * @description The ONE path from an approved proposal to a booking (single-use claim, then execute exactly once — ADR-0009). The request has NO body: the server-authoritative proposal is keyed by the token, and `actor` is fixed to `agent`; a client cannot supply either. 200 = a real actionable outcome (confirmed | held_unconfirmed); 202 = the winner is still executing (in_progress) — poll GET to resolve.
         */
        post: operations["redeemConfirmation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TurnRequest: {
            /** @description Continues an existing thread; server mints one if absent. NOT persisted (L4). */
            conversation_id?: string;
            /** @description The user's natural-language turn. */
            message: string;
        };
        TurnResponse: components["schemas"]["TurnTextReply"] | components["schemas"]["TurnFormFallbackReply"] | components["schemas"]["TurnToolReply"] | components["schemas"]["TurnProposalReply"];
        TurnTextReply: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            conversation_id: string;
            /** @description The model answered/clarified in text — no tool ran. */
            text: string;
        };
        TurnFormFallbackReply: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "form_fallback";
            conversation_id: string;
            /** @description Why extraction/validation failed — drop to the manual form. */
            reason: string;
            validation_errors?: string[];
        };
        TurnToolReply: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tool";
            conversation_id: string;
            /** @description The tool that ran (a live rates/booking endpoint). */
            tool: string;
            result: components["schemas"]["ToolResultView"];
        };
        TurnProposalReply: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "proposal";
            conversation_id: string;
            /** @description The SECRET confirmation credential (see TokenPath). Returned exactly once, here, in the response body; GET /confirmations never re-emits it. The client holds it in memory only. */
            token: string;
            card: components["schemas"]["CardState"];
        };
        ToolResultView: {
            ok: boolean;
            /** @description The upstream HTTP status, forwarded verbatim. */
            status: number;
            data?: {
                [key: string]: unknown;
            } | null;
            error?: {
                [key: string]: unknown;
            } | null;
        };
        CardState: {
            /** Format: uuid */
            confirmation_id: string;
            /** Format: uuid */
            quote_id: string;
            shipper_ref: string;
            /** @description Lifecycle of the confirmation row (e.g. pending, consumed, expired). */
            status: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: uuid */
            booking_id: string | null;
            final_status: string | null;
        };
        RedeemSettled: components["schemas"]["RedeemConfirmed"] | components["schemas"]["RedeemHeldUnconfirmed"];
        RedeemConfirmed: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "confirmed";
            /** Format: uuid */
            confirmation_id: string;
            /** Format: uuid */
            booking_id: string;
            /** @enum {string} */
            final_status: "CONFIRMED";
            /** @description True when this click re-observed an already-consumed row (idempotent re-click) — still a success, not an error. */
            replayed: boolean;
        };
        RedeemHeldUnconfirmed: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "held_unconfirmed";
            /** Format: uuid */
            confirmation_id: string;
            /** Format: uuid */
            booking_id: string;
            /** @description The booking's last known status (e.g. HELD). */
            final_status: string;
            /** @description Why confirm did not complete cleanly. */
            detail: string;
        };
        RedeemInProgress: {
            /** @enum {string} */
            status: "in_progress";
            /** Format: uuid */
            confirmation_id: string;
        };
        ErrorEnvelope: {
            /** @example CONFIRMATION_EXPIRED */
            code: string;
            message: string;
            details: string[];
        };
    };
    responses: {
        /** @description Uniform error envelope */
        ErrorResponse: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description The secret confirmation token: 32 random bytes, base64url — exactly 43 url-safe chars. Possession IS authorization (ADR-0009 Cond. F); it rides the path as a fetch credential and must never enter a navigable URL, browser history, logs, or a query-cache key. */
        TokenPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id, echoed from the request or minted if absent/invalid. */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description The turn's outcome (one of four arms; only `proposal` carries a token) */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
        };
    };
    getConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The secret confirmation token: 32 random bytes, base64url — exactly 43 url-safe chars. Possession IS authorization (ADR-0009 Cond. F); it rides the path as a fetch credential and must never enter a navigable URL, browser history, logs, or a query-cache key. */
                token: components["parameters"]["TokenPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The confirmation card (non-secret; no token field) */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardState"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
    redeemConfirmation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The secret confirmation token: 32 random bytes, base64url — exactly 43 url-safe chars. Possession IS authorization (ADR-0009 Cond. F); it rides the path as a fetch credential and must never enter a navigable URL, browser history, logs, or a query-cache key. */
                token: components["parameters"]["TokenPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redeemed — booking confirmed, or created-but-confirm-degraded (HELD) */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemSettled"];
                };
            };
            /** @description The concurrent winner is still executing; poll GET to resolve */
            202: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemInProgress"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
            410: components["responses"]["ErrorResponse"];
            502: components["responses"]["ErrorResponse"];
        };
    };
}
