/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a calculated quote (status ACTIVE, expires in 24h) */
        post: operations["createQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/{id}/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve a quote (quote_status ACTIVE → HELD) */
        post: operations["holdQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a booking from a HELD quote (idempotent). Lands the booking in HELD. */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a booking (booking_status HELD → CONFIRMED)
         * @description Actor-agnostic — booking-service stamps whatever actor the caller sends. The "user click only" gate is enforced upstream in agent-service's confirmation token (§6.3.2); the booking API is the same public API for UI and agent (§2.2).
         */
        post: operations["confirmBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a booking (QUOTED | HELD | CONFIRMED → CANCELLED) */
        post: operations["cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A booking with its full event timeline */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Actor: "user" | "agent" | "system";
        /** @enum {string} */
        QuoteStatus: "ACTIVE" | "HELD" | "EXPIRED" | "CONSUMED";
        /** @enum {string} */
        BookingStatus: "QUOTED" | "HELD" | "CONFIRMED" | "DOCUMENTS_ISSUED" | "EXPIRED" | "CANCELLED";
        /** @enum {string} */
        Mode: "OCEAN" | "AIR" | "TRUCK";
        ActorRequest: {
            actor: components["schemas"]["Actor"];
            /** @description Optional context (e.g. conversation_id for agent actions). */
            metadata?: {
                [key: string]: unknown;
            };
        };
        ShipmentSpec: {
            origin_code: string;
            dest_code: string;
            mode?: components["schemas"]["Mode"];
            /** Format: date */
            ship_date: string;
            /** Format: date */
            deliver_by?: string;
            cargo: components["schemas"]["Cargo"];
        };
        Cargo: {
            pallets?: number;
            weight_kg: number;
            volume_cbm?: number;
            description: string;
        };
        BreakdownLine: {
            /** @example FUEL */
            component: string;
            /** @enum {string|null} */
            calc?: "FLAT" | "PERCENT" | null;
            rate_bps?: number | null;
            /** Format: int64 */
            amount_cents: number;
        };
        CreateQuoteRequest: {
            /** Format: uuid */
            lane_id: string;
            /** Format: uuid */
            rate_card_id: string;
            shipment: components["schemas"]["ShipmentSpec"];
            breakdown: components["schemas"]["BreakdownLine"][];
            /** Format: int64 */
            total_cents: number;
            currency: string;
        };
        Quote: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lane_id: string;
            /** Format: uuid */
            rate_card_id: string;
            shipment: components["schemas"]["ShipmentSpec"];
            breakdown: components["schemas"]["BreakdownLine"][];
            /** Format: int64 */
            total_cents: number;
            currency: string;
            status: components["schemas"]["QuoteStatus"];
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateBookingRequest: {
            /** Format: uuid */
            quote_id: string;
            shipper_ref: string;
            actor: components["schemas"]["Actor"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quote_id: string;
            shipper_ref: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        BookingEvent: {
            from_status: components["schemas"]["BookingStatus"] | null;
            to_status: components["schemas"]["BookingStatus"];
            actor: components["schemas"]["Actor"];
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            at: string;
        };
        BookingDetail: {
            booking: components["schemas"]["Booking"];
            /** @description Append-only transition log, oldest first. */
            events: components["schemas"]["BookingEvent"][];
        };
        ErrorEnvelope: {
            /** @example ILLEGAL_TRANSITION */
            code: string;
            message: string;
            details: string[];
        };
    };
    responses: {
        /** @description Uniform error envelope */
        ErrorResponse: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdPath: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id, echoed from the request or minted if absent/invalid. */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuoteRequest"];
            };
        };
        responses: {
            /** @description Quote persisted */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    holdQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorRequest"];
            };
        };
        responses: {
            /** @description Quote held */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-supplied idempotency key (the agent reuses the confirmation token, §6.3). Replaying the same key returns the original booking (200) instead of creating a new one. First-write-wins — a divergent payload on replay is ignored, not rejected. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay — the original booking for this Idempotency-Key */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Booking created (now HELD) */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    confirmBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorRequest"];
            };
        };
        responses: {
            /** @description Booking confirmed */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorRequest"];
            };
        };
        responses: {
            /** @description Booking cancelled */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            409: components["responses"]["ErrorResponse"];
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking + ordered event timeline */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            404: components["responses"]["ErrorResponse"];
        };
    };
}
