/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/rates/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rate cards valid for a ship date on a lane */
        get: operations["searchRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quotes/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Full quote calculation with surcharge breakdown (pure, no persistence) */
        post: operations["calculateQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Mode: "OCEAN" | "AIR" | "TRUCK";
        /** @enum {string} */
        RateUnit: "PER_CONTAINER" | "PER_KG" | "PER_PALLET" | "PER_MILE";
        /** @enum {string} */
        SurchargeCalc: "FLAT" | "PERCENT";
        ShipmentSpec: {
            origin_code: string;
            dest_code: string;
            mode?: components["schemas"]["Mode"];
            /** Format: date */
            ship_date: string;
            /** Format: date */
            deliver_by?: string;
            cargo: components["schemas"]["Cargo"];
        };
        Cargo: {
            pallets?: number;
            weight_kg: number;
            volume_cbm?: number;
            description: string;
        };
        CalculateRequest: {
            /** Format: uuid */
            rate_card_id: string;
            shipment: components["schemas"]["ShipmentSpec"];
        };
        RateCardView: {
            /** Format: uuid */
            id: string;
            origin_code: string;
            origin_name: string;
            dest_code: string;
            dest_name: string;
            mode: components["schemas"]["Mode"];
            distance_mi?: number | null;
            /** Format: int64 */
            base_rate_cents: number;
            currency: string;
            unit: components["schemas"]["RateUnit"];
            transit_days_min: number;
            transit_days_max: number;
            /** Format: date */
            valid_from: string;
            /** Format: date */
            valid_to: string;
        };
        /** @description One line of the quote breakdown. component=BASE is the base cost; others are surcharge types. */
        BreakdownLine: {
            /** @example FUEL */
            component: string;
            calc?: components["schemas"]["SurchargeCalc"];
            /** @description basis points, present only when calc=PERCENT */
            rate_bps?: number | null;
            /** Format: int64 */
            amount_cents: number;
        };
        /** @description Cross-service contract — booking snapshots `breakdown`/`total_cents` into quotes.breakdown JSONB (§4.2). The breakdown lines sum exactly to total_cents. */
        QuoteResponse: {
            /** Format: uuid */
            rate_card_id: string;
            origin_code: string;
            dest_code: string;
            mode: components["schemas"]["Mode"];
            currency: string;
            /** Format: int64 */
            base_cost_cents: number;
            breakdown: components["schemas"]["BreakdownLine"][];
            /** Format: int64 */
            total_cents: number;
            transit_days_min: number;
            transit_days_max: number;
        };
        ErrorEnvelope: {
            /** @example RATE_NOT_FOUND */
            code: string;
            message: string;
            details: string[];
        };
    };
    responses: {
        /** @description Uniform error envelope */
        ErrorResponse: {
            headers: {
                /** @description Correlation id, echoed from the request or minted if absent/invalid. */
                "X-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchRates: {
        parameters: {
            query: {
                /** @example CNSHA */
                origin: string;
                /** @example USOAK */
                dest: string;
                mode: components["schemas"]["Mode"];
                /** @example 2026-08-01 */
                ship_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching rate cards (may be several — overlapping validity windows) */
            200: {
                headers: {
                    /** @description Correlation id, echoed from the request or minted if absent/invalid. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rate_cards: components["schemas"]["RateCardView"][];
                    };
                };
            };
            400: components["responses"]["ErrorResponse"];
        };
    };
    calculateQuote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateRequest"];
            };
        };
        responses: {
            /** @description Computed quote */
            200: {
                headers: {
                    /** @description Correlation id, echoed from the request or minted if absent/invalid. */
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
        };
    };
}
