import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Generate `src/prompt/v1_system.gen.ts` from the repo-root `prompts/v1_system.md`.
 *
 * WHY GENERATE RATHER THAN READ AT RUNTIME (guardian condition L5-C7 permits exactly two
 * resolutions; this is the second). `docker-compose.yml` builds agent-service with context
 * `./services/agent`, so the repo-root `prompts/` directory is OUTSIDE the build context and simply
 * is not present in the image. The other resolution, moving the build context to the repo root,
 * leaves the path asymmetric: `src/prompt/` sits four levels below the repo root while
 * `dist/prompt/` sits two levels below `/app`, so no single relative path resolves in both dev and
 * container. Closing that needs either a mirrored container layout or a resolver with fallbacks,
 * and a resolver that silently picks a candidate is hazard H3's failure mode. Generating the module
 * deletes the problem: the text lives inside `src`, which is already in the build context, and
 * nothing is read from disk at runtime.
 *
 * The `.md` REMAINS the source of truth (L5-C5). The generated module is committed as a tracked
 * file and CI regenerates it and runs `git diff --exit-code`, exactly as `gen:api` does for the
 * OpenAPI clients. LEARNING's rule applies: an uncommitted generated file makes the drift gate
 * toothless, because there is nothing for the diff to be against.
 *
 * The generated module records the SOURCE FILENAME alongside the text so `PROMPT_VERSION` can be
 * checked against it (L5-C4): swapping the prompt file without bumping the version must fail CI
 * rather than silently re-keying every fixture.
 */

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");

/** The one place the prompt filename is written. `PROMPT_VERSION` is checked against it. */
const PROMPT_FILENAME = "v1_system.md";

const source = join(repoRoot, "prompts", PROMPT_FILENAME);

/**
 * DERIVED from the source filename, never written out a second time.
 *
 * These were two independent literals, and both reviewers caught the same hole: at a v2 bump,
 * changing only the source name would regenerate v2 TEXT into a file still called
 * `v1_system.gen.ts`, `systemPrompt.ts` would keep importing `./v1_system.gen.js`, and
 * `PROMPT_SOURCE_FILENAME` would read `v2_system.md`. The L5-C4 test compares `PROMPT_SOURCE`
 * against `PROMPT_VERSION` and both sides would say v2, so it passes; `git diff src/prompt` passes
 * too. The result is a filename that lies about its contents, which is L5-C4's exact failure mode
 * displaced one level down.
 *
 * Deriving it also forces the `systemPrompt.ts` import path to move on a bump, which is the right
 * friction: a version bump SHOULD be a visible edit rather than a silent overwrite.
 */
const target = join(here, "..", "src", "prompt", `${PROMPT_FILENAME.replace(/\.md$/, "")}.gen.ts`);

/**
 * TRIMMED, because trimmed is what goes on the wire: `composeMessages` trims before building the
 * system message, so a trailing newline in the `.md` would otherwise make the module's bytes, the
 * sha256 in the boot log, and the bytes actually sent three subtly different things. Trimming once
 * here collapses them to one.
 */
const text = readFileSync(source, "utf8").trim();

if (text.length === 0) {
  throw new Error(`${source} is empty — refusing to generate a promptless module`);
}

const banner = `// GENERATED by scripts/gen-prompt.ts from prompts/${PROMPT_FILENAME}. Do not edit.
// Edit the .md and run \`pnpm gen:prompt\`. CI regenerates this and fails on any diff.`;

const body = `${banner}

/** The prompt file this text came from. Checked against PROMPT_VERSION (condition L5-C4). */
export const PROMPT_SOURCE_FILENAME = ${JSON.stringify(PROMPT_FILENAME)};

/** The system prompt, trimmed: byte-for-byte what composeMessages puts on the wire. */
export const PROMPT_TEXT = ${JSON.stringify(text)};
`;

writeFileSync(target, body);

const digest = createHash("sha256").update(text).digest("hex");
console.log(`gen:prompt → ${target}\n  source=${PROMPT_FILENAME} bytes=${Buffer.byteLength(text)} sha256=${digest}`);
